[package]
name = "donate"
version = "0.1.0"
authors = ["Created with Anchor"]
rust-version = "1.56"
edition = "2021"

[dependencies]
solana-program = "1.6.10"
anchor-lang = "0.23.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "donate"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]